import { Metadata } from "next";
import "./globals.css";

import Client from "@/components/Client";
import Nav from "@/components/Nav";
import Footer from "@/components/Footer";

export const metadata: Metadata = {
  title: "AVEGA",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={``}>
        <Nav />
        <Client>{children}</Client>
        <div className="h-[100vh] relative">w</div>
        <Footer />
      </body>
    </html>
  );
}
