import { Metadata } from "next";
import "./globals.css";

import Client from "@/components/Client";

export const metadata: Metadata = {
  title: "AVEGA",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={``}>
        <Client>{children}</Client>
      </body>
    </html>
  );
}
