import { Metadata } from "next";


export const metadata: Metadata = {
  title: "AVEGA - Fleet",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  fleet,
}: Readonly<{
  children: React.ReactNode;
  fleet: React.ReactNode;
}>) {
  return (
    <div lang="en">
      <div className={``}>
        {children}
        {fleet}
      </div>
    </div>
  );
}
