import { Metadata } from "next";


export const metadata: Metadata = {
  title: "AVEGA - Fleet",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  fleet,
}: Readonly<{
  children: React.ReactNode;
  fleet: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={``}>
        {children}
        {fleet}
      </body>
    </html>
  );
}
